{{- if .Values.security.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jena-fuseki.fullname" . }}-admin
  labels:
    {{- include "jena-fuseki.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.security.adminUser | quote }}
  password: {{ include "jena-fuseki.adminPassword" . | quote }}
{{- end }}
